AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: patterns-ddb-importer-v1

Parameters:
  InputBucketName:
    Type: String
    Default: 'security-price-12345'

Resources:
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName

  DDBtable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      - AttributeName: ticker
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: ticker
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Ref InputBucketName

  ImportFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdafunction/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 30
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBtable        
        - S3CrudPolicy:
            BucketName: !Ref InputBucketName
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputS3Bucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.json'            
